name: "0num4/Hello World"
description: "Greet someone and record the time"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
  github-pat-token:
    description: "GitHub PAT token"
    required: true
    default: ${{ secrets.GITHUB_PAT_TOKEN }}
  badges:
    description: "Badges"
    required: false
    default: "true"
  badge-style:
    description: "Badge style"
    required: false
    default: "flat"
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node20"
  main: "dist/index.js"
