name: hello-gh-actions
description: "Greet someone and record the time"
input:
  who-to-greet:
    description: "who to greet"
    required: true
    default: "world"
output:
  time:
    description: "the time we greeted you"
runs:
  using: "node20"
  main: "dist/index.js"
